name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - shell: bash
      env:
        USERNAME: ${{ secrets.USERNAME }}
      run: echo ${USERNAME}
        
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER-USERNAME }}
        password: ${{ secrets.DOCKER-PASSWORD }}
        
    - name: Permission
      run: chmod 744 gradlew
  
    - name: build
      run: ./gradlew clean build  
    
    
    - name: Build the Docker image
      run: docker build -t  ${{ secrets.DOCKER.USERNAME }}/ ${{ secrets.DOCKER.REPOSITORY}} . 
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}













        
