on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: print
      run: echo ${{env.secrets.DOCKER.REPOSITORY}}
    - name: print
      run: echo ${{env.env.DOCKER.hi}}
    - name: print
      run: echo ${{env.DOCKER.hi}}
    - name: print
      run: echo ${{env.DOCKER.secrets.REPOSITORY}}
    - name: print
      run: echo ${{env.DOCKER.env.hi}}
    - name: print
      run: echo ${{vars.DOCKER.secrets.REPOSITORY}}
    - name: print
      run: echo ${{vars.DOCKER.env.hi}}
    
