on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: print
      run: echo ${{env.DOCKER.secrets.REPOSITORY}}
    - name: print
      run: echo ${{env.secrets.DOCKER.PASSWORD}}
    
